version: '2'
services:
  db:
    container_name: db12basicmodel
    image: postgres:10
    environment:
    - POSTGRES_PASSWORD=odoo
    - POSTGRES_USER=odoo
    - POSTGRES_DB=postgres
    - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - db-data:/var/lib/postgresql/data/pgdata
    ports:
      - 5434:5434/tcp
  web:
    container_name: odoo12basicmodel
    image: odoo:12.0
    depends_on:
      - db
    ports:
      - "8069:8069/tcp"
    volumes:
      - web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
volumes:
  db-data:
    driver: local
  web-data:
    driver: local
